version: '3.8'

services:

  hermes-postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: hermes
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: hermes102030
      PGDATA: /pgdata/
    ports:
      - "5432:5432"
    volumes:
      - pg-volume:/pgdata/

  hermes-postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: hermes
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: hermes102030
      PGDATA: /pgdata/
    ports:
      - "5432:5432"
    volumes:
      - pg-volume:/pgdata/

  hermes-service:
    container_name: hermes-service
    image: 562044999811.dkr.ecr.us-east-2.amazonaws.com/hermes:${HERMES_VERSION:-latest}
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://hermes:hermes102030@localhost/hermes}
      - PYTHONBUFFERED=1
      - ENVIRONMENT=dev
    links:
      - hermes-postgres
    depends_on: 
      - hermes-postgres
    volumes:
      - ../../:/code/
    ports:
      - "8000:8000"
      
volumes:
  pg-volume:
  portainer_data: