version: '3.8'

services:

  hermes-postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: hermes
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: hermes102030
      PGDATA: /pgdata/
    ports:
      - "5432:5432"
    volumes:
      - pg-volume:/pgdata/

  hermes-postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: hermes
      POSTGRES_USER: hermes
      POSTGRES_PASSWORD: hermes102030
      PGDATA: /pgdata/
    ports:
      - "5432:5432"
    volumes:
      - pg-volume:/pgdata/

  hermes-rabbitmq:
    image: rabbitmq:3.8.10-management-alpine
    container_name: hermes-rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: hermes
        RABBITMQ_DEFAULT_PASS: hermes102030
    ports:
        - 15672:15672

  hermes-service:
    container_name: hermes-service
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    environment:
      - PYTHONBUFFERED=1
      - ENVIRONMENT=dev
    links:
      - hermes-postgres
      - hermes-rabbitmq
    depends_on: 
      - hermes-postgres
      - hermes-rabbitmq
    volumes:
      - ../../:/code/
    ports:
      - "5000:5000"
      - "5443:5443"
      - "8080:8080"
      
volumes:
  pg-volume:
  portainer_data: