version: 2
jobs:
  build_and_test:
    resource_class: small
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - run:
          command: |
            echo "$(head -n +1 requirements/base.txt)" > requirements/a.txt
            echo "$(tail -n +2 requirements/base.txt)" > requirements/b.txt
            echo "$(tail -n +2 requirements/development.txt)" > requirements/dev.txt
      - restore_cache:
          keys:
            - k9-{{ .Branch }}-{{ checksum "requirements/b.txt" }}-{{ checksum "requirements/development.txt" }}
      - run:
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install wheel
            pip install urllib3
            pip install -r requirements/b.txt
            pip install -r requirements/dev.txt
      - save_cache:
          key: k9-{{ .Branch }}-{{ checksum "requirements/b.txt" }}-{{ checksum "requirements/development.txt" }}
          paths:
            - venv
      - run:
          command: |
            source venv/bin/activate
            pip install -r requirements/a.txt
            pytest -s | tee /tmp/results.log
      - store_test_results:
          path: /tmp/results.log

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test:
          context:
            - AWS
